development:
  adapter: postgresql
  database: sample_app
  username: postgres

test:
  adapter: postgresql
  database: sample_app
  username: postgres

production:
  adapter: postgresql
  database: sample_app
  username: postgres